function [weightInput, weightHidden, weightOutput] = ...
    FormWeightsBasic(weightLinear, dim, nHidden, nLabel)

    weightInput = reshape(weightLinear(1: dim * nHidden(1)), ...
        dim, nHidden(1));
    offset = dim * nHidden(1);
    weightHidden = cell(length(nHidden) - 1);
    for indexHidden = 2: length(nHidden)
        weightHidden{indexHidden - 1} = ...
            reshape(weightLinear(offset + 1: offset + ...
            nHidden(indexHidden - 1) * nHidden(indexHidden)), ...
            nHidden(indexHidden - 1), nHidden(indexHidden));
        offset = offset + nHidden(indexHidden - 1) * nHidden(indexHidden);
    end
    weightOutput = reshape(weightLinear(offset + 1: offset + ...
        nHidden(end) * nLabel), nHidden(end), nLabel);
end