function [weightInput, weightHidden, weightOutput] = ...
    FormWeightsBiased(weightLinear, dim, nHidden, nLabel)

    weightInput = reshape(weightLinear(1: dim * (nHidden(1) - 1)), ...
        dim, (nHidden(1) - 1));
    offset = dim * (nHidden(1) - 1);
    weightHidden = cell(length(nHidden) - 1);
    for indexHidden = 2: length(nHidden)
        weightHidden{indexHidden - 1} = ...
            reshape(weightLinear(offset + 1: offset + ...
            nHidden(indexHidden - 1) * (nHidden(indexHidden) - 1)), ...
            nHidden(indexHidden - 1), (nHidden(indexHidden) - 1));
        offset = offset + ...
            nHidden(indexHidden - 1) * (nHidden(indexHidden) - 1);
    end
    weightOutput = reshape(weightLinear(offset + 1: offset + ...
        nHidden(end) * nLabel), nHidden(end), nLabel);
end