function [weightsInput, weightsHidden, weightsOutput] = ...
    FormWeightsBiased(weights, dim, nHidden, nLabel)

    weightsInput = reshape(weights(1: dim * (nHidden(1) - 1)), ...
        dim, (nHidden(1) - 1));
    offset = dim * (nHidden(1) - 1);
    weightsHidden = cell(length(nHidden) - 1);
    for indexHidden = 2: length(nHidden)
        weightsHidden{indexHidden - 1} = reshape(weights(offset + 1: ...
            offset + nHidden(indexHidden - 1) * ...
            (nHidden(indexHidden) - 1)), ...
            nHidden(indexHidden - 1), (nHidden(indexHidden) - 1));
        offset = offset + nHidden(indexHidden - 1) * ...
            (nHidden(indexHidden) - 1);
    end
    weightsOutput = reshape(weights(offset + 1: ...
        offset + nHidden(end) * nLabel), nHidden(end), nLabel);
end